version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: lib_manage
      POSTGRES_USER: lib_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lib_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - lib_network

  celery:
    build: .
    command: celery -A core.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - lib_network

  redis:
    image: redis:alpine
    networks:
      - lib_network

networks:
  lib_network:

volumes:
  postgres_data:
